const inquirer = require('inquirer');
const chalk = require('chalk');
const { requireAuth, setAuth } = require('./auth');
const { executeWithFailover } = require('./api');
const { checkAllModelsHealth } = require('./health');
const { showSessionPanel, showModelComparison, formatAIResponse, showInfoBox, showErrorBox } = require('./ui');
const { getConfig } = require('./config');

const AVAILABLE_MODELS = ['gpt-4o', 'claude', 'gemini'];

let state = {
    model: 'gpt-4o',
    status: 'Active',
    autoFailover: true
};

async function startStudio() {
    await requireAuth();

    // Load project config if available
    const config = getConfig();
    if (config) {
        if (config.defaultModel) state.model = config.defaultModel;
        if (config.autoFailover !== undefined) state.autoFailover = config.autoFailover;
    }

    showSessionPanel(state.model, state.status, state.autoFailover);
    await studioLoop();
}

async function handleCommand(input) {
    const cmd = input.trim().toLowerCase();

    switch (cmd) {
        case ':exit':
            console.log(chalk.cyan('\nExiting Forge Studio. Goodbye!\n'));
            process.exit(0);
            break;

        case ':clear':
            console.clear();
            showSessionPanel(state.model, state.status, state.autoFailover);
            break;

        case ':auto':
            state.autoFailover = !state.autoFailover;
            showInfoBox(`Auto-failover is now ${state.autoFailover ? 'ON' : 'OFF'}`);
            showSessionPanel(state.model, state.status, state.autoFailover);
            break;

        case ':model':
            const { selectedModel } = await inquirer.prompt([{
                type: 'list',
                name: 'selectedModel',
                message: 'Select a primary model:',
                choices: AVAILABLE_MODELS
            }]);
            state.model = selectedModel;
            showSessionPanel(state.model, state.status, state.autoFailover);
            break;

        case ':models':
            console.log(chalk.cyan('\nAvailable models configuration goes here.\n'));
            break;

        case ':test all':
            const results = await checkAllModelsHealth();
            showModelComparison(results);
            break;

        case ':test':
            state.status = 'Testing...';
            showSessionPanel(state.model, state.status, state.autoFailover);
            try {
                await executeWithFailover('hello', state.model, false);
                state.status = 'Active';
            } catch (e) {
                state.status = 'Offline';
            }
            showSessionPanel(state.model, state.status, state.autoFailover);
            break;

        case ':key':
            const { key } = await inquirer.prompt([{
                type: 'password',
                name: 'key',
                message: `Enter new Prompt Forge API Key:`,
                mask: '*'
            }]);
            setAuth(key);
            showInfoBox(`Prompt Forge API Key updated.`);
            break;

        default:
            if (cmd.startsWith(':')) {
                showErrorBox('Unknown Command', `Command ${cmd} not recognized. Type :exit to quit.`);
            } else {
                // Handle prompt generation
                try {
                    const result = await executeWithFailover(input, state.model, state.autoFailover);

                    if (result.metadata.model !== state.model) {
                        // It failed over to a different model!
                        showInfoBox(`Response was generated by fallback model: ${result.metadata.model}`);
                        if (state.autoFailover) {
                            state.status = 'Degraded';
                            showSessionPanel(state.model, state.status, state.autoFailover);
                        }
                    }

                    formatAIResponse(result.text, result.metadata);
                } catch (error) {
                    showErrorBox('Generation Failed', error.message);
                    if (!state.autoFailover) {
                        console.log(chalk.cyan('Hint: Try running `:test all` to check model health, or enable auto-failover with `:auto`.\n'));
                    }
                    state.status = 'Offline';
                    showSessionPanel(state.model, state.status, state.autoFailover);
                }
            }
    }
}

async function studioLoop() {
    while (true) {
        const { promptInput } = await inquirer.prompt([
            {
                type: 'input',
                name: 'promptInput',
                message: chalk.cyan('forge> '),
                prefix: ''
            }
        ]);

        if (!promptInput.trim()) continue;

        await handleCommand(promptInput);
    }
}

module.exports = {
    startStudio
};
