ALTER TABLE public.v2_execution_logs
ADD COLUMN IF NOT EXISTS tokens_input INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS tokens_output INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS cost_micro_usd INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS ab_test_variant TEXT;
